# This is a basic workflow to help you get started with Actions

name: commento_shopping_CI_CD

# Controls when the workflow will run
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install dependencies.
        run: |
            npm ci
            npm install

      # Runs a set of commands using the runners shell
      - name: Execute build.
        run: npm run build
          
